### PR TITLE
Let's do the first release

### PR DESCRIPTION
**Pull request by FroMage**

### CODE REVIEW

**Comment by FroMage** [comment]
@radcortez could you check I got the coordinates/smallrye parts right?
@geoand do you want to check the package names, docs? you don't have to, but I feel safer with a review.

It's not strictly _in_ this PR, but the initial commit didn't get reviewed so :shrug:

**Comment by radcortez** [comment]
> @radcortez could you check I got the coordinates/smallrye parts right?

+1

**Review by radcortez — APPROVED** [review]

**Comment by geoand** [comment]
Sure thing, I'll check tomorrow morning

**Comment by geoand** [comment]
LGTM!

**Comment by FroMage** [comment]
Let's see if this releases!

**Comment by radcortez** [comment]
Yes: https://repo1.maven.org/maven2/io/smallrye/smallrye-safer-annotations/1.0.1/

**Comment by FroMage** [comment]
Oh great. So how many people does it take to notice that we now have:

`io.smallrye:smallrye-safer-annotations` and:
`io.smallrye.common:smallrye-common-annotation` with completely different name conventions?

:(

**Comment by FroMage** [comment]
So… do we :shrug: and look the other way, or do I swallow my pride and either pivot towards merging safer-annotations into `sr-common-annotations` or rename this module to a more consistent `io.smallrye.safer:smallrye-safer-annotation`?

**Comment by FroMage** [comment]
The `groupId` is inconsistent but also the singular/plural of `annotation` in the name and package.

**Comment by geoand** [comment]
> So… do we 🤷 and look the other way, or do I swallow my pride and either pivot towards merging safer-annotations into `sr-common-annotations` or rename this module to a more consistent `io.smallrye.safer:smallrye-safer-annotation`?

Hm... Maybe go with the latter?

**Comment by FroMage** [comment]
That'd be fine by me, but I'd like to double check with @radcortez perhaps @kenfinnigan and whoever is the maintainer of `smallrye-common-annotation`?

**Comment by FroMage** [comment]
@Ladicek @jmartisk and @cescoffier it seems.

Actually it appears that `smallrye-common-annotation` is a submodule of `io.smallrye.common` which contains a lot more modules than just annotations, so perhaps the difference in `groupId` is actually fine?

It does however lead me to wonder if this whole thing should not just go into `smallrye-common`, but I can't decide that.

**Comment by Ladicek** [comment]
I don't think SmallRye Common has a designated set of maintainers :-)

Some SmallRye projects have a groupId of `io.smallrye.something`, while others have a groupId of simply `io.smallrye`. So far, I haven't considered that a problem.

**Comment by kenfinnigan** [comment]
The main usage in the past for a separate suffix after `io.smallrye` for groupId was where a single project would create many artifacts, such as reactive messaging, vs a small number.

The concern was needing to segregate the namespace so that there weren't 40-50 artifacts under a single groupId

**Comment by radcortez** [comment]
We discussed the namespace for this here:
https://github.com/quarkusio/quarkus/pull/14731#issuecomment-782108628

As for these annotations being part of `smallrye-common` I had the impression we had that discussion and we decided to be a separate project, but I can't find it anywhere. Maybe it was in a meeting. But I also can't remember the reason.

**Comment by Ladicek** [comment]
We have hundreds of artifacts under `io.quarkus`, so having a few dozens under `io.smallrye` isn't something I would lose sleep over :-) We still attempt globally unique artifactIds (perhaps with the exception of a few projects in `io.smallrye.reactive`), so I personally don't really care about the groupId. It's only there because it needs to be there.

**Comment by radcortez** [comment]
Anyway, does anyone remember a good reason to have a separate project for these annotations?

**Comment by dmlloyd** [comment]
This is an annotation processor, with a couple of associated annotations; SmallRye Common doesn't do annotation processing. That's the main reason to me.

**Comment by radcortez** [comment]
Ah, yes! Exactly. Thanks @dmlloyd !

@FroMage I think we are ok as is.

**Comment by FroMage** [comment]
OK cool. Let's stick to this `groupId`. But I still think the `artifactId` is not in line with `smallrye-common-annotation` due to plural/singular.

On the other hand, `smallrye-safer-annotation` sounds awfully like there's only a single annotation. So let's just keep this as-is and call it a day and point people to this discussion later.

**Pull request merged**
